spring.application.name=elpapelillo

# Configuración del servidor SMTP de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elpapelillocarnaval@gmail.com
spring.mail.password=vmxy enza iniy ceyy

# Propiedades adicionales
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# URL: localhost:3306 / Nombre de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/elpapelillo_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

# Las credenciales que pusiste en el instalador
spring.datasource.username=root
spring.datasource.password=Abc12def

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Esto obliga a Hibernate a usar el nombre EXACTO que pones en @Column
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Esto evita que Hibernate intente deducir nombres lógicos distintos
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE